// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld/helloworld.proto

package helloworld

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HellpoRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,32,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HellpoRequest) Reset()         { *m = HellpoRequest{} }
func (m *HellpoRequest) String() string { return proto.CompactTextString(m) }
func (*HellpoRequest) ProtoMessage()    {}
func (*HellpoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73149fedf49f4319, []int{0}
}

func (m *HellpoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HellpoRequest.Unmarshal(m, b)
}
func (m *HellpoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HellpoRequest.Marshal(b, m, deterministic)
}
func (m *HellpoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HellpoRequest.Merge(m, src)
}
func (m *HellpoRequest) XXX_Size() int {
	return xxx_messageInfo_HellpoRequest.Size(m)
}
func (m *HellpoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HellpoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HellpoRequest proto.InternalMessageInfo

func (m *HellpoRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HellpoRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type HelloResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73149fedf49f4319, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HellpoRequest)(nil), "helloworld.HellpoRequest")
	proto.RegisterType((*HelloResponse)(nil), "helloworld.HelloResponse")
}

func init() {
	proto.RegisterFile("helloworld/helloworld.proto", fileDescriptor_73149fedf49f4319)
}

var fileDescriptor_73149fedf49f4319 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x86, 0x29, 0x7e, 0xac, 0x0e, 0x08, 0x92, 0x53, 0xd5, 0x4b, 0xd9, 0xd3, 0x7a, 0x48, 0x03,
	0x8a, 0x77, 0x59, 0x04, 0x05, 0x6f, 0xf1, 0xe6, 0x2d, 0x4d, 0x86, 0xb4, 0x6c, 0x92, 0x89, 0x49,
	0xd6, 0x8f, 0x7f, 0x2f, 0xdb, 0x45, 0x5b, 0xf1, 0xf6, 0x24, 0x33, 0x0f, 0xf3, 0xf2, 0xc2, 0x55,
	0x8f, 0xce, 0xd1, 0x07, 0x25, 0x67, 0xc4, 0x84, 0x6d, 0x4c, 0x54, 0x88, 0xc1, 0xf4, 0xb3, 0xbc,
	0x83, 0xb3, 0x27, 0x74, 0x2e, 0x92, 0xc4, 0xb7, 0x2d, 0xe6, 0xc2, 0x18, 0x1c, 0x06, 0xe5, 0xb1,
	0xae, 0x9a, 0x6a, 0x75, 0x2a, 0x47, 0x66, 0xe7, 0x70, 0xa0, 0x2c, 0xd6, 0x4d, 0x53, 0xad, 0x8e,
	0xe4, 0x0e, 0x97, 0xd7, 0x7b, 0x8d, 0x24, 0xe6, 0x48, 0x21, 0x23, 0xab, 0x61, 0xe1, 0x31, 0xe7,
	0xdd, 0xda, 0xde, 0xfc, 0x79, 0xde, 0x3c, 0xc3, 0xe2, 0x31, 0x21, 0x16, 0x4c, 0xec, 0x1e, 0x4e,
	0x5e, 0xd4, 0xd7, 0x28, 0xb2, 0x8b, 0x76, 0x96, 0xeb, 0x4f, 0x84, 0xcb, 0x7f, 0xa3, 0xdf, 0x33,
	0xeb, 0x87, 0xd7, 0xb5, 0x1d, 0x4a, 0xbf, 0xed, 0x5a, 0x4d, 0x5e, 0x6c, 0x86, 0xa4, 0x02, 0xef,
	0x1c, 0xe9, 0x8d, 0xee, 0xd5, 0x10, 0x44, 0xc0, 0xf2, 0x69, 0xb8, 0x25, 0xae, 0xcc, 0xbb, 0x0a,
	0x1a, 0x8d, 0xb0, 0x29, 0x6a, 0x6e, 0xd0, 0xd3, 0xac, 0x86, 0xee, 0x78, 0xec, 0xe1, 0xf6, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0xde, 0x0d, 0x52, 0x3b, 0x26, 0x01, 0x00, 0x00,
}
