// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task/task.proto

package task

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Task struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tittle               string   `protobuf:"bytes,2,opt,name=tittle,proto3" json:"tittle,omitempty"`
	Completted           bool     `protobuf:"varint,3,opt,name=completted,proto3" json:"completted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f2b86464a95fe, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetTittle() string {
	if m != nil {
		return m.Tittle
	}
	return ""
}

func (m *Task) GetCompletted() bool {
	if m != nil {
		return m.Completted
	}
	return false
}

type TaskResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskResponse) Reset()         { *m = TaskResponse{} }
func (m *TaskResponse) String() string { return proto.CompactTextString(m) }
func (*TaskResponse) ProtoMessage()    {}
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f2b86464a95fe, []int{1}
}

func (m *TaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskResponse.Unmarshal(m, b)
}
func (m *TaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskResponse.Marshal(b, m, deterministic)
}
func (m *TaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskResponse.Merge(m, src)
}
func (m *TaskResponse) XXX_Size() int {
	return xxx_messageInfo_TaskResponse.Size(m)
}
func (m *TaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskResponse proto.InternalMessageInfo

func (m *TaskResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TaskList struct {
	Tasks                []*Task  `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskList) Reset()         { *m = TaskList{} }
func (m *TaskList) String() string { return proto.CompactTextString(m) }
func (*TaskList) ProtoMessage()    {}
func (*TaskList) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f2b86464a95fe, []int{2}
}

func (m *TaskList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskList.Unmarshal(m, b)
}
func (m *TaskList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskList.Marshal(b, m, deterministic)
}
func (m *TaskList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskList.Merge(m, src)
}
func (m *TaskList) XXX_Size() int {
	return xxx_messageInfo_TaskList.Size(m)
}
func (m *TaskList) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskList.DiscardUnknown(m)
}

var xxx_messageInfo_TaskList proto.InternalMessageInfo

func (m *TaskList) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f2b86464a95fe, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Task)(nil), "task.Task")
	proto.RegisterType((*TaskResponse)(nil), "task.TaskResponse")
	proto.RegisterType((*TaskList)(nil), "task.TaskList")
	proto.RegisterType((*Empty)(nil), "task.Empty")
}

func init() {
	proto.RegisterFile("task/task.proto", fileDescriptor_8e8f2b86464a95fe)
}

var fileDescriptor_8e8f2b86464a95fe = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcd, 0x4b, 0xf4, 0x30,
	0x10, 0xc6, 0x69, 0xf7, 0xab, 0xef, 0xf4, 0x65, 0x85, 0x1c, 0xa4, 0xec, 0x61, 0x29, 0xbd, 0x58,
	0xc1, 0xb6, 0x50, 0xcf, 0x22, 0x0a, 0xe2, 0x45, 0x3c, 0x54, 0x4f, 0xde, 0xd2, 0x64, 0xe8, 0x86,
	0x7e, 0xa4, 0x34, 0xe3, 0xa2, 0xff, 0xbd, 0x24, 0xab, 0x58, 0xbc, 0x84, 0xe4, 0x79, 0x32, 0x3f,
	0x7e, 0x0c, 0x9c, 0x11, 0x37, 0x6d, 0x61, 0x8f, 0x7c, 0x9c, 0x34, 0x69, 0xb6, 0xb4, 0xf7, 0xe4,
	0x19, 0x96, 0xaf, 0xdc, 0xb4, 0x6c, 0x0b, 0xbe, 0x92, 0x91, 0x17, 0x7b, 0xe9, 0xbf, 0xca, 0x57,
	0x92, 0x9d, 0xc3, 0x9a, 0x14, 0x51, 0x87, 0x91, 0xef, 0xb2, 0xef, 0x17, 0xdb, 0x03, 0x08, 0xdd,
	0x8f, 0x1d, 0x12, 0xa1, 0x8c, 0x16, 0xb1, 0x97, 0x06, 0xd5, 0x2c, 0x49, 0xf6, 0xf0, 0xdf, 0xf2,
	0x2a, 0x34, 0xa3, 0x1e, 0x0c, 0xfe, 0xe5, 0x26, 0x57, 0x10, 0xd8, 0xfe, 0x49, 0x19, 0x62, 0x31,
	0xac, 0xac, 0x83, 0x89, 0xbc, 0x78, 0x91, 0x86, 0x25, 0xe4, 0xce, 0xce, 0x8d, 0x9f, 0x8a, 0x64,
	0x03, 0xab, 0x87, 0x7e, 0xa4, 0xcf, 0x92, 0x43, 0x68, 0xf3, 0x17, 0x9c, 0x8e, 0x4a, 0x20, 0xbb,
	0x84, 0xcd, 0x9d, 0x94, 0x4e, 0x7c, 0x36, 0xb5, 0x63, 0x33, 0xc2, 0x8f, 0xc0, 0x05, 0x04, 0x8f,
	0x48, 0x36, 0x32, 0x2c, 0x3c, 0xf5, 0x0e, 0xb9, 0xdb, 0xfe, 0x7e, 0xb6, 0x36, 0xf7, 0xb7, 0x6f,
	0x37, 0x8d, 0xa2, 0xc3, 0x7b, 0x9d, 0x0b, 0xdd, 0x17, 0xad, 0x9a, 0xf8, 0x90, 0xd5, 0x9d, 0x16,
	0xad, 0x38, 0x70, 0x35, 0x14, 0x03, 0xd2, 0x87, 0xcc, 0x1a, 0x9d, 0x71, 0x79, 0xe4, 0x83, 0x40,
	0x59, 0x34, 0xd3, 0x28, 0x32, 0x89, 0xbd, 0x2e, 0xdd, 0x5a, 0xeb, 0xb5, 0xdb, 0xeb, 0xf5, 0x57,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x72, 0x57, 0xb2, 0x6a, 0x01, 0x00, 0x00,
}
